version: '2'

services:

  data:
    image: busybox
    volumes:
     - ../:/src
     - ~/.cache/yarn/:/home/user/.cache/yarn
     - ~/.cache/bower/:/home/user/.cache/bower

  cli:
    image: node:8
    entrypoint: bash
    working_dir: /src
    volumes_from:
      - data

  web_dev:
    command: "bash -c 'yarn serve'"
    image: node:8
    ports:
      - 8080:8080
    volumes_from:
      - data
    working_dir: /src